import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SolWalletProvider from "@/providers/SolWalletProvider";
import AppProvider from "@/providers/AppProvider";
import { cookies } from "next/headers";
import "@solana/wallet-adapter-react-ui/styles.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')
  let user:  any | null = null;

  return (
    <html lang="en">
      <body className={inter.className}>
      <SolWalletProvider>
          <AppProvider initialAccessToken={accessToken?.value} user={user}>
         
          {children}
         
        
          </AppProvider>
       </SolWalletProvider>
      </body>
    </html>
  );
}
