import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/providers/AppProvider";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/toaster";
import { AptosProvider } from "@/providers/AptosContext";
import SuiWalletProvider from "@/providers/SuiWalletProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')
  let user:  any | null = null;

  return (
    <html lang="en">
      <body className={inter.className}>
      <AptosProvider>
          <SuiWalletProvider>
            <AppProvider initialAccessToken={accessToken?.value} user={user}>
              <Toaster />
              {children}
            </AppProvider>
          </SuiWalletProvider>
        </AptosProvider>
      </body>
    </html>
  );
}
